jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_PARTICIPANT
        ROLE_SUPER_ADMIN: [ROLE_PARTICIPANT, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
           entity:
               class:  PhotoAssessmentBundle:User
               property: id

    firewalls:
        main:
          pattern: ^/
          security: true
          anonymous: ~
          provider: main
          form_login: ~
          remember_me:
               lifetime: 315360000
               domain:   ~
               path:     /
               key:      %remember_me_token%
               name:     %remember_me_cookie%
               always_remember_me: true
               remember_me_parameter: _remember_me
               secure: false
          
#          http_digest:
#               provider: main
#               key: main

#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false

#        login:
#            pattern:  ^/demo/secured/login$
#            security: false
#
#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: /demo/secured/login_check
#                login_path: /demo/secured/login
#            logout:
#                path:   /demo/secured/logout
#                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

#    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
