parameters:
    pat.queue_first_photo_id: -1
    pat.queue_initial_size: 50
    pat.queue_extension_size: 25
    pat.geograph_dir: %kernel.root_dir%/../web/content/geograph
    pat.ask_location: false
