services:

    kachkaev_counters.listener.counters_on_off:
        class: Kachkaev\CountersBundle\Listener\CountersOnOffListener
        tags:
            -  { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    kachkaev_counters.twig.counters:
        class: Kachkaev\CountersBundle\Twig\CountersExtension
        arguments: [@service_container]
        tags:
            -  { name: twig.extension }